import React from 'react'
import bg from '@/assets/images/header/privacy.jpg'
import Image from 'next/image'
import ButtonWrapper from '@/components/common/ButtonWrapper'

export const metadata = {
   title: 'Privacy Policy',
   description: 'Generated by create next app',
}

export default function Privacy() {
   return (
      <>
         <main>
            <Image src={bg} alt="truck" className="header__img" width={1300} height={350} placeholder='blur' quality={90} />
            <section className="main__privacy privacy">
               <div className="container">
                  <div className="privacy__inner">
                     <div className="max-w-[800px]">
                        <h2 className="clients__title title"><span>Privacy</span> Policy</h2>
                        <p className="privacy__text">It is a long established fact that a reader will be distracted by the
                           readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it
                           has a more-or-less normal distribution of letters, as opposed to using 'Content here, content
                           here', making it look like readable English. Many desktop publishing packages and web page editors
                           now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many
                           web sites still in their infancy.
                        </p>
                        <h5 className="privacy__subtitle">Some subtitle
                        </h5>
                        <p className="privacy__text">Lorem Ipsum is simply dummy text of the printing and typesetting
                           industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                           unknown printer took a galley of type and scrambled it to make a type specimen book. It has
                           survived not only five centuries, remaining essentially unchanged. It was popularised in the 1960s.
                        </p>
                        <h5 className="privacy__subtitle">Some subtitle
                        </h5>
                        <p className="privacy__text">There are many variations of passages of Lorem Ipsum available, but
                           the majority have suffered alteration in some form, by injected humour, or randomised words which
                           don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to
                           be sure there isn't anything embarrassing hidden in the middle of text.If you are going to use a
                           passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle
                           of text.
                        </p>
                        <ButtonWrapper href="/" className='mt-[50px]'>Back to home</ButtonWrapper>
                     </div>
                  </div>
               </div>
            </section>
         </main>
      </>
   )
}
