import Benefits from "@/components/Benefits/Benefits";
import Blog from "@/components/Blog/Blog";
import Clients from "@/components/Clients/Clients";
import Intro from "@/components/Intro/Intro";
import Mission from "@/components/Mission/Mission";
import Services from "@/components/Services/Services";
import Team from "@/components/Team/Team";
import { benefits, imgData, news, services, sliderData, team } from "@/helpers/localData";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: 'Center Logistic',
  description: 'Generated by create next app',
}

export default function Home() {

  return (
    <>
      <main className="main">
        <Intro />
        <section
          className="main__service"
          id="service"
        >
          <Services data={services} />
        </section>
        <section className="main__clients" id="clients">
          <Clients
            imgData={imgData}
            sliderData={sliderData}
          />
        </section>
        <section className="main__benefits" id="benefits">
          <Benefits data={benefits} />
        </section>
        <section className="main__team" id="team">
          <Team data={team} />
        </section>
        <section className="main__mission">
          <Mission />
        </section>
        <section className="main__news" id="news">
          <Blog data={news} />
        </section>
      </main>
    </>
  );
}
