import Clients from "@/components/Clients/Clients";
import Intro from "@/components/Intro/Intro";
import Services from "@/components/Services/Services";
import { imgData, services, sliderData } from "@/helpers/localData";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: 'Center Logistic',
  description: 'Generated by create next app',
}

export default function Home() {

  return (
    <>
      <main className="main">
        <Intro />

        <section
          className="main__service service"
          id="service"
        >
          <Services data={services} />
        </section>

        <section
          className="main__clients clients"
          id="clients"
        >
          <Clients
            imgData={imgData}
            sliderData={sliderData}
          />
        </section>

        {/* <section className="main__benefits benefits" id="benefits" data-scrollspy="#benefits">
          <div className="container">
            <div className="benefits__inner">
              <div className="benefits__content">
                <ul className="benefits__list">
                  {benefits.map((item, key) => (
                    <li key={key} className="benefits__list-item">
                      <h4 className="benefits__list-title">{item.title}</h4>
                      <p className="benefits__list-text">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
                        nonumy eirmod tempor </p>
                    </li>
                  ))}
                </ul>
              </div>
              <div className="benefits__img-box" data-aos="fade-left" data-aos-delay="200">
                <img src="images/way-truck.jpg" alt="truck" className="benefits__img" />
              </div>
            </div>
          </div>
        </section> */}

        {/* <section className="main__team team" id="team" data-scrollspy="#team">
          <div className="container">
            <h2 className="team__title title" data-aos="fade-down"><span>Our</span> Team</h2>
            <div className="team__inner">
              <ul className="team__content-list">
                {team.map((item, key) => (
                  <li key={key} className="team__content-item">
                    <div className="team__img-box">
                      <img src={item.image} alt="John" className="team__img" />
                    </div>
                    <h4 className="team__item-title">{item.name}</h4>
                    <p className="team__item-subtitle">{item.position}</p>
                    <div className="team__mail">
                      <img src="images/icons/mail-black.svg" alt="mail" className="team__mail-img" />
                      <a href="mailto:john@centerlogistic.com" className="team__mail-link">{item.email}</a>
                    </div>
                    <div className="team__phone">
                      <img src="images/icons/phone-black.svg" alt="phone" className="team__phone-img" />
                      <a href="tel:987412512543" className="team__phone-link">{item.phone}</a>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </section> */}

        {/* <section className="main__mission mission">
          <div className="container">
            <div className="mission__content-wrapper">
              <h2 className="mission__title">Our mission</h2>
              <div className="mission__inner" data-aos="fade-up">
                <h3 className="mission__inner-title">To provide our customer qualified services according the
                  international</h3>
                <p className="mission__inner-subtitle">Book your Cargo now & Your job just got a lot easier</p>
                <div className="mission__lines">
                  <div className="mission__blue-line"></div>
                  <div className="mission__orange-line"></div>
                </div>
              </div>
            </div>
            <div className="mission__button-wrapper">
              <a href="#" target="_blank" className="mission__button button">Become a client</a>
            </div>
          </div>
        </section> */}

        {/* <section className="main__news news" id="news" data-scrollspy="#news">
          <div className="container">
            <h2 className="clients__title title" data-aos="fade-down"><span>Interesting</span> to read</h2>
            <ul className="news__list">
              <li className="news__list-item" data-aos="flip-down">
                <article className="news__list-article">
                  <a className="news__item-link" href="#">
                    <h4 className="news__item-title">News title</h4>
                    <p className="news__item-text">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                      diam
                      nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
                      voluptua.
                      At
                      vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
                      takimata sanctus est Lorem ipsum dolor sit amet.</p>
                    <time dateTime="21-03-2019" className="news__item-time">21 March, 2019</time>
                  </a>
                </article>
              </li>
              <li className="news__list-item" data-aos="flip-down">
                <article className="news__list-article">
                  <a className="news__item-link" href="#">
                    <h4 className="news__item-title">News title</h4>
                    <p className="news__item-text">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                      diam
                      nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
                      voluptua.
                      At
                      vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
                      takimata sanctus est Lorem ipsum dolor sit amet.</p>
                    <time dateTime="21-03-2019" className="news__item-time">21 March, 2019</time>
                  </a>
                </article>
              </li>
            </ul>
            <a href="news.html" className="news__button button" data-aos="fade-up">Visit blog</a>
          </div>
        </section> */}
      </main>
    </>
  );
}
