import Benefits from "@/components/Benefits/Benefits";
import Clients from "@/components/Clients/Clients";
import Intro from "@/components/Intro/Intro";
import Mission from "@/components/Mission/Mission";
import Services from "@/components/Services/Services";
import Team from "@/components/Team/Team";
import { benefits, imgData, services, sliderData, team } from "@/helpers/localData";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: 'Center Logistic',
  description: 'Generated by create next app',
}

export default function Home() {

  return (
    <>
      <main className="main">
        <Intro />

        <section
          className="main__service service"
          id="service"
        >
          <Services data={services} />
        </section>

        <section className="main__clients clients" id="clients">
          <Clients
            imgData={imgData}
            sliderData={sliderData}
          />
        </section>

        <section className="main__benefits benefits" id="benefits">
          <Benefits data={benefits} />
        </section>

        <section className="main__team team" id="team">
          <Team data={team} />
        </section>

        <section className="main__mission mission">
          <Mission />
        </section>

        {/* <section className="main__news news" id="news">
          <div className="container">
            <h2 className="clients__title title" ><span>Interesting</span> to read</h2>
            <ul className="news__list">
              <li className="news__list-item" >
                <article className="news__list-article">
                  <a className="news__item-link" href="#">
                    <h4 className="news__item-title">News title</h4>
                    <p className="news__item-text">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                      diam
                      nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
                      voluptua.
                      At
                      vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
                      takimata sanctus est Lorem ipsum dolor sit amet.</p>
                    <time dateTime="21-03-2019" className="news__item-time">21 March, 2019</time>
                  </a>
                </article>
              </li>
              <li className="news__list-item">
                <article className="news__list-article">
                  <a className="news__item-link" href="#">
                    <h4 className="news__item-title">News title</h4>
                    <p className="news__item-text">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                      diam
                      nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
                      voluptua.
                      At
                      vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
                      takimata sanctus est Lorem ipsum dolor sit amet.</p>
                    <time dateTime="21-03-2019" className="news__item-time">21 March, 2019</time>
                  </a>
                </article>
              </li>
            </ul>
            <a href="news.html" className="news__button button">Visit blog</a>
          </div>
        </section> */}
      </main>
    </>
  );
}
