import React from 'react'
import bg from '@/assets/images/header/interesting.jpg'
import Image from 'next/image'
import ButtonWrapper from '@/components/common/ButtonWrapper'
import IntroForm from '@/components/Intro/IntroForm'
import { news } from '@/helpers/localData'
import Title from '@/components/common/Title'

export const metadata = {
   title: 'Our blog',
   description: 'Generated by create next app',
}

export default function News() {
   return (
      <main>
         <Image src={bg} alt="truck" className="header__img" width={1300} height={350} placeholder='blur' quality={90} />
         <section className="main__blog max-phone:!pb-0">
            <div className="container">
               <div className="flex justify-between gap-4 max-phone:flex-col max-phone:gap-12 max-phone:items-center">
                  <div className="blog__content">
                     <div className="flex flex-col gap-[45px] max-w-[600px] max-phone:max-w-full max-phone:gap-3">
                        <Title blueText="Interesting" blackText="to read" />
                        {news.map((item, key) => (
                           <article key={key} className="news__list-item">
                              <a className="news__item-link" href="/news">
                                 <h4 className="news__item-title">{item.title}</h4>
                                 <p className="news__item-text">{item.text}</p>
                                 <time dateTime="21-03-2019" className="news__item-time">{item.date}</time>
                              </a>
                           </article>
                        ))}
                     </div>
                     <ButtonWrapper href="/" className='mt-[50px] max-phone:mt-[30px]'>Back to home</ButtonWrapper>
                  </div>
                  <div className="form !h-fit">
                     <div className="form__head">
                        <h3 className="head__title">Get Callback</h3>
                        <h5 className="head__subtitle">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
                           nonumy eirmod tempor invidunt ut</h5>
                     </div>
                     <IntroForm />
                  </div>
               </div>
            </div>
         </section>
      </main>
   )
}
